---
name: learn-bosh

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

releases:
- name: learn-bosh
  version: latest

update:
  canaries: 1
  max_in_flight: 2
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

instance_groups:
- name: app
  instances: 1
  azs: [z1, z2, z3]
  jobs:
  - {name: app, release: learn-bosh}
  vm_type: default
  stemcell: default
  networks:
  - name: default
    static_ips:
    - 10.244.0.2
  properties: {}

- name: simple-errand
  azs: [z1]
  lifecycle: errand
  instances: 1
  jobs:
  - {name: smoke-tests, release: learn-bosh}
  vm_type: default
  stemcell: default
  networks:
  - name: default
